name: check_snapshots
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check that snapshots have been verified manually
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'Snapshot tests pass') }}
        run: |
          echo "Missing required label: Snapshot tests pass"
          exit 1
