name: run_tests
on:
  pull_request:
jobs:
  run_tests:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          submodules: recursive

      - name: Setup CMake
        uses: threeal/cmake-action@v2.1.0

      - name: Build
        run: cmake --build build --config Debug

      - name: Run unit tests
        run: ./build/Debug/UnitTests.exe

      - name: Check that snapshots have been verified manually
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'Snapshot tests pass') }}
        run: |
          echo "Missing required label: Snapshot tests pass"
          exit 1
