name: run_tests
on:
  pull_request:
jobs:
  run_tests:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          submodules: recursive

      # Mesa is used to support OpenGL on windows-latest
      - name: Download Mesa
        shell: pwsh
        run: |
          $url = "https://github.com/pal1000/mesa-dist-win/releases/download/23.1.9/mesa3d-23.1.9-release-msvc.7z"
          Invoke-WebRequest $url -OutFile mesa.7z
          7z x mesa.7z -omesa

      - name: Setup CMake
        uses: threeal/cmake-action@v2.1.0

      - name: Build
        run: cmake --build build --config Debug

      - name: Setup Mesa
        shell: pwsh
        run: |
          Copy-Item mesa/x64/*.dll build/Debug/ -Force
          echo "LIBGL_ALWAYS_SOFTWARE=1" >> $env:GITHUB_ENV

      - name: Run tests
        run: ./build/Debug/Tests.exe
